// Code generated by protoc-gen-go-cosmos-orm. DO NOT EDIT.

package modulev1

import (
	context "context"
	ormlist "cosmossdk.io/orm/model/ormlist"
	ormtable "cosmossdk.io/orm/model/ormtable"
	ormerrors "cosmossdk.io/orm/types/ormerrors"
)

type AccountTable interface {
	Insert(ctx context.Context, account *Account) error
	Update(ctx context.Context, account *Account) error
	Save(ctx context.Context, account *Account) error
	Delete(ctx context.Context, account *Account) error
	Has(ctx context.Context, address string) (found bool, err error)
	// Get returns nil and an error which responds true to ormerrors.IsNotFound() if the record was not found.
	Get(ctx context.Context, address string) (*Account, error)
	List(ctx context.Context, prefixKey AccountIndexKey, opts ...ormlist.Option) (AccountIterator, error)
	ListRange(ctx context.Context, from, to AccountIndexKey, opts ...ormlist.Option) (AccountIterator, error)
	DeleteBy(ctx context.Context, prefixKey AccountIndexKey) error
	DeleteRange(ctx context.Context, from, to AccountIndexKey) error

	doNotImplement()
}

type AccountIterator struct {
	ormtable.Iterator
}

func (i AccountIterator) Value() (*Account, error) {
	var account Account
	err := i.UnmarshalMessage(&account)
	return &account, err
}

type AccountIndexKey interface {
	id() uint32
	values() []interface{}
	accountIndexKey()
}

// primary key starting index..
type AccountPrimaryKey = AccountAddressIndexKey

type AccountAddressIndexKey struct {
	vs []interface{}
}

func (x AccountAddressIndexKey) id() uint32            { return 0 }
func (x AccountAddressIndexKey) values() []interface{} { return x.vs }
func (x AccountAddressIndexKey) accountIndexKey()      {}

func (this AccountAddressIndexKey) WithAddress(address string) AccountAddressIndexKey {
	this.vs = []interface{}{address}
	return this
}

type accountTable struct {
	table ormtable.Table
}

func (this accountTable) Insert(ctx context.Context, account *Account) error {
	return this.table.Insert(ctx, account)
}

func (this accountTable) Update(ctx context.Context, account *Account) error {
	return this.table.Update(ctx, account)
}

func (this accountTable) Save(ctx context.Context, account *Account) error {
	return this.table.Save(ctx, account)
}

func (this accountTable) Delete(ctx context.Context, account *Account) error {
	return this.table.Delete(ctx, account)
}

func (this accountTable) Has(ctx context.Context, address string) (found bool, err error) {
	return this.table.PrimaryKey().Has(ctx, address)
}

func (this accountTable) Get(ctx context.Context, address string) (*Account, error) {
	var account Account
	found, err := this.table.PrimaryKey().Get(ctx, &account, address)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, ormerrors.NotFound
	}
	return &account, nil
}

func (this accountTable) List(ctx context.Context, prefixKey AccountIndexKey, opts ...ormlist.Option) (AccountIterator, error) {
	it, err := this.table.GetIndexByID(prefixKey.id()).List(ctx, prefixKey.values(), opts...)
	return AccountIterator{it}, err
}

func (this accountTable) ListRange(ctx context.Context, from, to AccountIndexKey, opts ...ormlist.Option) (AccountIterator, error) {
	it, err := this.table.GetIndexByID(from.id()).ListRange(ctx, from.values(), to.values(), opts...)
	return AccountIterator{it}, err
}

func (this accountTable) DeleteBy(ctx context.Context, prefixKey AccountIndexKey) error {
	return this.table.GetIndexByID(prefixKey.id()).DeleteBy(ctx, prefixKey.values()...)
}

func (this accountTable) DeleteRange(ctx context.Context, from, to AccountIndexKey) error {
	return this.table.GetIndexByID(from.id()).DeleteRange(ctx, from.values(), to.values())
}

func (this accountTable) doNotImplement() {}

var _ AccountTable = accountTable{}

func NewAccountTable(db ormtable.Schema) (AccountTable, error) {
	table := db.GetTable(&Account{})
	if table == nil {
		return nil, ormerrors.TableNotFound.Wrap(string((&Account{}).ProtoReflect().Descriptor().FullName()))
	}
	return accountTable{table}, nil
}

type IdentityTable interface {
	Insert(ctx context.Context, identity *Identity) error
	Update(ctx context.Context, identity *Identity) error
	Save(ctx context.Context, identity *Identity) error
	Delete(ctx context.Context, identity *Identity) error
	Has(ctx context.Context, did string) (found bool, err error)
	// Get returns nil and an error which responds true to ormerrors.IsNotFound() if the record was not found.
	Get(ctx context.Context, did string) (*Identity, error)
	List(ctx context.Context, prefixKey IdentityIndexKey, opts ...ormlist.Option) (IdentityIterator, error)
	ListRange(ctx context.Context, from, to IdentityIndexKey, opts ...ormlist.Option) (IdentityIterator, error)
	DeleteBy(ctx context.Context, prefixKey IdentityIndexKey) error
	DeleteRange(ctx context.Context, from, to IdentityIndexKey) error

	doNotImplement()
}

type IdentityIterator struct {
	ormtable.Iterator
}

func (i IdentityIterator) Value() (*Identity, error) {
	var identity Identity
	err := i.UnmarshalMessage(&identity)
	return &identity, err
}

type IdentityIndexKey interface {
	id() uint32
	values() []interface{}
	identityIndexKey()
}

// primary key starting index..
type IdentityPrimaryKey = IdentityDidIndexKey

type IdentityDidIndexKey struct {
	vs []interface{}
}

func (x IdentityDidIndexKey) id() uint32            { return 0 }
func (x IdentityDidIndexKey) values() []interface{} { return x.vs }
func (x IdentityDidIndexKey) identityIndexKey()     {}

func (this IdentityDidIndexKey) WithDid(did string) IdentityDidIndexKey {
	this.vs = []interface{}{did}
	return this
}

type identityTable struct {
	table ormtable.Table
}

func (this identityTable) Insert(ctx context.Context, identity *Identity) error {
	return this.table.Insert(ctx, identity)
}

func (this identityTable) Update(ctx context.Context, identity *Identity) error {
	return this.table.Update(ctx, identity)
}

func (this identityTable) Save(ctx context.Context, identity *Identity) error {
	return this.table.Save(ctx, identity)
}

func (this identityTable) Delete(ctx context.Context, identity *Identity) error {
	return this.table.Delete(ctx, identity)
}

func (this identityTable) Has(ctx context.Context, did string) (found bool, err error) {
	return this.table.PrimaryKey().Has(ctx, did)
}

func (this identityTable) Get(ctx context.Context, did string) (*Identity, error) {
	var identity Identity
	found, err := this.table.PrimaryKey().Get(ctx, &identity, did)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, ormerrors.NotFound
	}
	return &identity, nil
}

func (this identityTable) List(ctx context.Context, prefixKey IdentityIndexKey, opts ...ormlist.Option) (IdentityIterator, error) {
	it, err := this.table.GetIndexByID(prefixKey.id()).List(ctx, prefixKey.values(), opts...)
	return IdentityIterator{it}, err
}

func (this identityTable) ListRange(ctx context.Context, from, to IdentityIndexKey, opts ...ormlist.Option) (IdentityIterator, error) {
	it, err := this.table.GetIndexByID(from.id()).ListRange(ctx, from.values(), to.values(), opts...)
	return IdentityIterator{it}, err
}

func (this identityTable) DeleteBy(ctx context.Context, prefixKey IdentityIndexKey) error {
	return this.table.GetIndexByID(prefixKey.id()).DeleteBy(ctx, prefixKey.values()...)
}

func (this identityTable) DeleteRange(ctx context.Context, from, to IdentityIndexKey) error {
	return this.table.GetIndexByID(from.id()).DeleteRange(ctx, from.values(), to.values())
}

func (this identityTable) doNotImplement() {}

var _ IdentityTable = identityTable{}

func NewIdentityTable(db ormtable.Schema) (IdentityTable, error) {
	table := db.GetTable(&Identity{})
	if table == nil {
		return nil, ormerrors.TableNotFound.Wrap(string((&Identity{}).ProtoReflect().Descriptor().FullName()))
	}
	return identityTable{table}, nil
}

type StateStore interface {
	AccountTable() AccountTable
	IdentityTable() IdentityTable

	doNotImplement()
}

type stateStore struct {
	account  AccountTable
	identity IdentityTable
}

func (x stateStore) AccountTable() AccountTable {
	return x.account
}

func (x stateStore) IdentityTable() IdentityTable {
	return x.identity
}

func (stateStore) doNotImplement() {}

var _ StateStore = stateStore{}

func NewStateStore(db ormtable.Schema) (StateStore, error) {
	accountTable, err := NewAccountTable(db)
	if err != nil {
		return nil, err
	}

	identityTable, err := NewIdentityTable(db)
	if err != nil {
		return nil, err
	}

	return stateStore{
		accountTable,
		identityTable,
	}, nil
}
